---
title: "R Notebook"
output: html_notebook
---



```{r}
library("readxl")
library(tidyr)
library(dplyr)

```


```{r, loadData}
column_names <- c(
  "trueStatement",
  "contextT",
  "syntaxT",
  "falseStatement",
  "contextF",
  "sytaxF",        
  "specifityF",
  "plausebilityF",
  "logicF",
  "falsabilityF",
  "difficultyF"
)


df_agrar <- read_excel("Agriculture_Seidel.xlsx")
df_ped <- read_excel("test1.xlsx")
df_info <- read_excel("test1.xlsx")
df_cs <- read_excel("test1.xlsx")

colnames(df_agrar) <- column_names
colnames(df_ped) <- column_names
colnames(df_info) <- column_names
colnames(df_cs) <- column_names
 
df_agrar 
```
```{r, aggregateData}

aggregateData <- function(data){
  data <- df_agrar
  names(data)
  data %>% 
    replace(is.na(.), 0) %>% select(contextT,syntaxT,contextF,sytaxF,specifityF,plausebilityF,logicF,falsabilityF,difficultyF) %>%
    mutate(difficultyF = difficultyF / 10) %>%
    tidyr::pivot_longer(cols=ends_with("F"), names_to = "variable", values_to = "count") %>%
    dplyr::select(variable, count) %>%
    group_by(variable) %>%
    summarise(n=sum(count)/(nrow(data)-1)) %>%
    mutate(n=round(n,2))
}

res_agrar <- aggregateData(df_agrar)
res_ped <- aggregateData(df_ped)
res_info <- aggregateData(df_info)
res_cs <- aggregateData(df_cs)
  
```

```{r, combinedresults}

res <- cbind(res_agrar, rowOrder=c(1, 7, 6, 5, 4, 3, 2))
#res <- res_agrar
res %>% 
  rename(Agriculture = n) %>%
  right_join(res_cs, by=c('variable')) %>%
  rename(Computer_Science = n) %>%
  right_join(res_info, by=c('variable')) %>%
  rename(Economics = n) %>%
  right_join(res_ped, by=c('variable')) %>%
  rename(Pedagogy = n) %>%
  arrange(rowOrder) %>% 
  select(-rowOrder) %>%
  mutate(Total = (Agriculture + Computer_Science + Economics + Pedagogy) / 4)

```

